FROM debian:12
WORKDIR /root/

LABEL "maintainer"="Evgenii Sopov <mrseakg@gmail.com>"
LABEL "repository"="https://github.com/sea5kg/ctf01d-automation-training"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libcurl4 \
    zlib1g \
    libpthread-stubs0-dev \
    locales \
    && apt-get clean

# RUN locale-gen en_US.UTF-8
RUN sed -i -e "s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
